---
title: "Hake MSE Exploration of OM"
subtitle: "Compare recruitment and reference points"
author: "Chris"
institute: "Brainstorming"
date: "Slides compiled on `r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: ["default", "xaringan-themer.css", "inline-code.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
header-includes:
  - \usepackage{animate}
---

```{r setup, include=FALSE, echo=FALSE, fig.width=8, fig.height=8}
# paste this into the console before running `xaringan::inf_mr("twg_01.Rmd")`
# to make your entries faster (fraction of a second)
# options(servr.interval = 0.1)

fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.asp = fig_asp,
  fig.width = fig_width,
  fig.path = "_bookdown_files/knitr-cache/",
  cache.path = "_bookdown_files/knitr-cache/",
  echo = FALSE,
  cache.comments = FALSE,
  dev = "png",
  dpi = fig_dpi,
  fig.align = fig_align
)

options(htmltools.dir.version = FALSE)
library(dplyr)
library(ggplot2)
library(devtools)
library(gridExtra)
library(here)
library(knitr)
load_all("../../pacifichakemse")

# Make all inline numeric values have comma separator for thousands
knit_hooks$set(inline = function(x){
  if(!is.numeric(x)){
    x
  }else{
    prettyNum(x, big.mark = ",")
  }
})

theme_set(hake_theme())

overwrite_rds <- FALSE
short_term_yrs <- 2018:2027
long_term_yrs <- 2027
main_results_dir <- "results"

# No catch, no recruitment and no HCR applied
if(!exists("ps_attainment_norecr_hcr")){
  ps_attainment_norecr_hcr <- load_mse_plot_data(
    scenario = "om_attainment_norecr_hcr",
    om_only = TRUE,
    overwrite_rds = overwrite_rds,
    short_term_yrs = short_term_yrs,
    long_term_yrs = long_term_yrs,
    main_results_dir = main_results_dir)
}

# 1,000,000 t catch, no recruitment and no HCR applied
if(!exists("ps_1e6_catch_norecr_nohcr")){
ps_1e6_catch_norecr_nohcr <- load_mse_plot_data(
  scenario = "om_attainment_1e6_catch_norecr_nohcr",
  om_only = TRUE,
  overwrite_rds = overwrite_rds,
  short_term_yrs = short_term_yrs,
  long_term_yrs = long_term_yrs,
  main_results_dir = main_results_dir)
}

# 1,000,000 t catch, recruitment and HCR applied
if(!exists("ps_recr_hcr")){
ps_recr_hcr <- load_mse_plot_data(
  scenario = "om_attainment_recr_hcr",
  om_only = TRUE,
  overwrite_rds = overwrite_rds,
  short_term_yrs = short_term_yrs,
  long_term_yrs = long_term_yrs,
  main_results_dir = main_results_dir)
}

ci_lines <- TRUE
start_yr <- 2008

```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#1c5253",# Matte green
  #base_color = "#cc6600ff", # Fall orange
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "300", "300i"),
  code_font_google   = google_font("Fira Mono")
)
```

---
class: center, middle, inverse

# Operating model only, no Estimation model

---
class: center
### No recruitment, default catch, default HCR
```{r zero-catch-zero-recr-hcr-ssb, out.width = 450}
plot_timeseries(ps_attainment_norecr_hcr,
                type = "ssb",
                ci_lines = ci_lines,
                yr_lim = c(start_yr, NA),
                ylim = c(0, NA),
                legend_position = c(0.18, 0.85))
```
```{r zero-catch-zero-recr-hcr-catch, out.width = 450}
plot_timeseries(ps_attainment_norecr_hcr,
                type = "catch",
                ci_lines = ci_lines,
                yr_lim = c(start_yr, NA),
                ylim = c(0, NA),
                legend_position = c(0.85, 0.85))
```

---
class: center
### Recruitment, default catch, default HCR
```{r recr-hcr-ssb, out.width = 450}
plot_timeseries(ps_recr_hcr,
                type = "ssb",
                ci_lines = ci_lines,
                yr_lim = c(start_yr, NA),
                ylim = c(0, 5),
                legend_position = c(0.18, 0.85))
```
```{r recr-hcr-catch, out.width = 450}
plot_timeseries(ps_recr_hcr,
                type = "catch",
                ci_lines = ci_lines,
                yr_lim = c(start_yr, NA),
                ylim = c(0, 2),
                legend_position = c(0.18, 0.85))
```

---
class: center
### No recruitment, 1e6 t catch, no HCR
```{r zero-recr-zero-hcr-ssb, out.width = 450}
plot_timeseries(ps_1e6_catch_norecr_nohcr,
                type = "ssb",
                ci_lines = ci_lines,
                yr_lim = c(start_yr, NA),
                ylim = c(0, 5),
                legend_position = c(0.18, 0.85))
```
```{r zero-recr-zero-hcr-catch, out.width = 450}
plot_timeseries(ps_1e6_catch_norecr_nohcr,
                type = "catch",
                ci_lines = ci_lines,
                yr_lim = c(start_yr, NA),
                ylim = c(0, 2),
                legend_position = c(0.18, 0.85))
```
