---
title: "MSE attainment results for n = 100 runs"
date: "Nov 22, 2020"
output: 
  rmarkdown::pdf_document:
    fig_caption: yes
    includes:
      in_header: header.tex
urlcolor: blue
---

```{r setup-r-env, include = FALSE}
library(devtools)
library(gridExtra)
library(here)
library(knitr)
load_all("../../pacifichakemse")
#library(pacifichakemse)

knitr_figs_dir <- "knitr-figs-pdf/"
knitr_cache_dir <- "knitr-cache-pdf/"
fig_out_type <- "pdf"
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  fig.pos = "!H",
  out.extra = "",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos)

# Make all inline numeric values have comma separator for thousands
knit_hooks$set(inline = function(x){
  if(!is.numeric(x)){
    x
  }else{
    prettyNum(x, big.mark = ",")
  }
})

theme_set(hake_theme())

overwrite_rds <- FALSE
ps <- create_plot_objects(scenarios = c("attainment_1",
                                        "attainment_2"),
                          om_only = c(FALSE, FALSE),
                          main_results_dir = "results",
                          overwrite_rds = overwrite_rds,
                          short_term_yrs = 2018:2027,
                          long_term_yrs = 2027)
ps1 <- ps[[1]]
ps2 <- ps[[2]]

#ps1$plotnames <- c("0% coastwide",
#                   "100% coastwide",
#                   "100% CA, 0% US",
#                   "100%US, 0% CA")
#ps2$plotnames <- c("0% coastwide",
#                   "10-yr-avg",
#                   "90% US, 56% CA",
#                   "60% US, 56% CA",
#                   "77% US, 70% CA",
#                   "77% US, 90% CA")
```

# Attainment scenarios with 0% and 100% attainment (Items 1-4)

```{r tacv-attain, fig.cap = "TAC / Vulnerable biomass by season and country."}
plot_bars_country(ps1,
                  facet_back_alpha = 50)
```

```{r ssb-attain, fig.cap = "Attainment scenarios SSB in middle of the year."}
yr_start <- 2010
plot_timeseries(ps1,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                legend_position = c(0.22, 0.85))
```

```{r ssb-attain-country, fig.cap = "Attainment scenarios SSB in middle of the year by country."}
yr_start <- 2010
plot_timeseries(ps1,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                show_40_10 = FALSE,
                legend_position = c(0.08, 0.9))
```

```{r ssb-ssb0-attain, fig.cap = "Attainment scenarios relative spawning biomass."}
plot_timeseries(ps1,
                type = "ssb_ssb0",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                legend_position = c(0.22, 0.85))
```

```{r catch-quota-attain, fig.cap = "Attainment scenarios catch / quota."}
plot_timeseries(ps1,
                type = "catch_quota",
                ci_lines = TRUE,
                yr_lim = c(yr_start, NA),
                legend_position = c(0.22, 0.15))
```

<!--
```{r catch-quota-attain-table}
yr_start <- 2019
table_timeseries(ps1,
                 type = "catch_quota",
                 yr_lim = c(yr_start, NA),
                 scen = 1:4,
                 decimals = 2,
                 caption = "Catch / quota for the Attainment scenarios.") %>% 
    kableExtra::kable_styling(font_size = 6)
```
-->

```{r pmetrics-attain, fig.cap = "Attainment scenarios violin plots of performace metrics."}
plot_violins(ps1)
```

```{r pmetrics-attain-table-1}
table_perf_metrics(ps1, 
                   decimals = 3,
                   scen = 1:2,
                   caption = "Performance metrics for the Attainment scenarios.") %>% 
      kableExtra::kable_styling(font_size = 8)
```

```{r pmetrics-attain-table-2}
table_perf_metrics(ps1, 
                   decimals = 3,
                   scen = 3:4,
                   #scen_names = c("A", "B", "C", "D"),
                   caption = "Performance metrics for the Attainment scenarios.") %>% 
      kableExtra::kable_styling(font_size = 8)
```

```{r exploitation-attain, fig.cap = "Attainment scenarios violin plots of exploitation rates by country. The three violin plots represent spring, summer, and fall respectively."}
plot_violins_country(ps1, facet_back_alpha = 50)
```

```{r catch-attain, fig.cap = "Attainment scenarios future projections of catch."}
#yr_start <- NA_real_
yr_start <- 2010
plot_timeseries(ps1,
                type = "catch",
                yr_lim = c(yr_start, NA),
                ci_lines = FALSE,
                legend_position = c(0.22, 0.85))
```

```{r aa-catch-attain, fig.cap = "Attainment scenarios average age in the true population."}
yr_start <- 2010
plot_timeseries(ps1,
                type = "aap",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                legend_position = c(0.22, 0.85))
```

```{r aap-table-1}
yr_start <- 2045
table_timeseries(ps1,
                 type = "aap",
                 yr_lim = c(yr_start, NA),
                 scen = 1:2,
                 decimals = 2,
                 caption = "Average age in the population for the Unfished and Full attainment scenarios.")
```

```{r aap-table-2}
yr_start <- 2045
table_timeseries(ps1,
                 type = "aap",
                 yr_lim = c(yr_start, NA),
                 scen = 3:4,
                 decimals = 2,
                 caption = "Average age in the population for the scenarios representing Full/Zero attainments for CAN/US.")
```

```{r aa-catch-country-attain, fig.cap = "Attainment scenarios average age in the true population by country."}
yr_start <- 2010
plot_timeseries(ps1,
                type = "aap",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                facet_back_alpha = 50,
                legend_position = c(0.08, 0.9))
```

```{r aap-bycountry-attain-table-1}
yr_start <- 2045
table_timeseries(ps1,
                 type = "aap",
                 yr_lim = c(yr_start, NA),
                 scen = 1,
                 decimals = 2,
                 by_country = TRUE,
                 caption = "Average age in the population by country for the unfished scenario.")
```

```{r aap-bycountry-attain-table-2}
yr_start <- 2045
table_timeseries(ps1,
                 type = "aap",
                 yr_lim = c(yr_start, NA),
                 scen = 2,
                 decimals = 2,
                 by_country = TRUE,
                 caption = "Average age in the population by country for the full attainment coastwide scenario.")
```

```{r aap-bycountry-attain-table-3}
yr_start <- 2045
table_timeseries(ps1,
                 type = "aap",
                 yr_lim = c(yr_start, NA),
                 scen = 3,
                 decimals = 2,
                 by_country = TRUE,
                 caption = "Average age in the population by country for the full attainment Canada, zero in the US scenario.")
```

```{r aap-bycountry-attain-table-4}
yr_start <- 2045
table_timeseries(ps1,
                 type = "aap",
                 yr_lim = c(yr_start, NA),
                 scen = 4,
                 decimals = 2,
                 by_country = TRUE,
                 caption = "Average age in the population by country for the full attainment US, zero in Canada scenario.")
```

```{r std-err-attain, fig.cap = "Attainment scenarios standard error of estimated to real spawning stock biomass."}
plot_standard_error(ps1,
                    facet_back_alpha = 50)
```

\clearpage 

# Attainment scenarios with other attainment (Items 1 and 5-9)

<!--
```{r tacv-attain-other, fig.cap = "TAC / Vulnerable biomass by season and country."}
plot_bars_country(ps2,
                  facet_back_alpha = 50)
```
-->

```{r ssb-attain-other, fig.cap = "Attainment scenarios SSB in middle of the year."}
yr_start <- 2010
plot_timeseries(ps2,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                legend_position = c(0.25, 0.8)) #+
  #coord_cartesian(xlim = c(2045, 2048), ylim = c(0, 1))
  
```

```{r ssb-attain-other-country, fig.cap = "Attainment scenarios SSB in middle of the year by country."}
yr_start <- 2010
plot_timeseries(ps2,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                show_40_10 = FALSE,
                legend_position = c(0.08, 0.9))
```

```{r ssb-ssb0-attain-other, fig.cap = "Attainment scenarios relative spawning biomass."}
plot_timeseries(ps2,
                type = "ssb_ssb0",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                legend_position = c(0.25, 0.80))
```

```{r catch-quota-attain-other, fig.cap = "Attainment scenarios catch / quota."}
plot_timeseries(ps2,
                type = "catch_quota",
                ci_lines = TRUE,
                yr_lim = c(yr_start, NA),
                legend_position = c(0.25, 0.2))
```

```{r catch-quota-attain-other-table}
yr_start <- 2019
table_timeseries(ps2,
                 type = "catch_quota",
                 yr_lim = c(yr_start, NA),
                 scen = 1:3,
                 decimals = 3,
                 caption = "Catch / quota for the Attainment scenarios.") %>% 
    kableExtra::kable_styling(font_size = 9)
```

```{r pmetrics-attain-other, fig.cap = "Attainment scenarios violin plots of performace metrics."}
plot_violins(ps2)
```

```{r pmetrics-attain-other-table}
table_perf_metrics(ps2, 
                   decimals = 3,
                   scen = c(1, 3),
                   caption = "Performance metrics for the Attainment scenarios.") %>% 
      kableExtra::kable_styling(font_size = 7)
```

```{r exploitation-attain-other, fig.cap = "Attainment scenarios violin plots of exploitation rates by country. The three violin plots represent spring, summer, and fall respectively."}
plot_violins_country(ps2, facet_back_alpha = 50)
```

```{r catch-attain-other, fig.cap = "Attainment scenarios future projections of catch."}
#yr_start <- NA_real_
yr_start <- 2010
plot_timeseries(ps2,
                type = "catch",
                yr_lim = c(yr_start, NA),
                ci_lines = FALSE,
                legend_position = c(0.25, 0.80))
```

```{r aa-catch-attain-other, fig.cap = "Attainment scenarios average age in catch."}
plot_timeseries(ps2,
                type = "aac",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                legend_position = c(0.25, 0.80))
```

```{r aa-catch-country-attain-other, fig.cap = "Attainment scenarios average age in catch by country."}
plot_timeseries(ps2,
                type = "aac",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                facet_back_alpha = 50,
                legend_position = c(0.08, 0.9))
```

```{r aa-catch-bycountry-attain-other-table}
yr_start <- 2040
table_timeseries(ps2,
                 type = "aac",
                 yr_lim = c(yr_start, NA),
                 scen = 1,
                 decimals = 2,
                 by_country = TRUE,
                 caption = "Average age in the catch by country for the base Attainment scenario.")
```

```{r std-err-attain-other, fig.cap = "Attainment scenarios standard error of estimated to real spawning stock biomass."}
plot_standard_error(ps2,
                    facet_back_alpha = 50)
```

