---
title: "MSE results for n = 20 runs"
date: "Nov 13, 2020"
output: 
  rmarkdown::pdf_document:
    fig_caption: yes
    includes:
      in_header: header.tex
urlcolor: blue
---

```{r setup-r-env, include = FALSE}
library(devtools)
library(gridExtra)
library(here)
library(knitr)
load_all("../../pacifichakemse")
#library(pacifichakemse)

knitr_figs_dir <- "knitr-figs-pdf/"
knitr_cache_dir <- "knitr-cache-pdf/"
fig_out_type <- "pdf"
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  fig.pos = "!H",
  out.extra = "",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos)

# Make all inline numeric values have comma separator for thousands
knit_hooks$set(inline = function(x){
  if(!is.numeric(x)){
    x
  }else{
    prettyNum(x, big.mark = ",")
  }
})

theme_set(hake_theme())

overwrite_rds <- FALSE
ps <- create_plot_objects(scenarios = c("biasadjust",
                                        "climate",
                                        "hcr",
                                        "selectivity"),
                          om_only = c(TRUE, FALSE, FALSE, FALSE),
                          main_results_dir = "results",
                          overwrite_rds = overwrite_rds,
                          short_term_yrs = 2018:2027,
                          long_term_yrs = 2027)
# Now ps is a list of 4 scenarios:
# biasadjust
ps_b <- ps[[1]]
# climate
ps_c <- ps[[2]]
# hcr values
ps_h <- ps[[3]]
# selectivity
ps_s <- ps[[4]]
```

# Biasadjust scenario

```{r ssb-biasadjust, fig.cap = "Equilibrium biomass in the future without fishing. The three different colors represent different bias adjustments, and the shaded area is the 5th and 95th percentiles (100 iterations). The dashed lines represent unfished spawning biomass SSB0, 0.4SBB0, and 0.1SSB0."}
yr_start <- 2010
plot_timeseries(ps_b,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                rev_scenarios = TRUE)
```

```{r ssb-ssb0-biasadjust087-table}
yr_start <- 2019
table_timeseries(ps_b,
                 type = "ssb_ssb0",
                 yr_lim = c(yr_start, NA),
                 scen = 1,
                 decimals = 3,
                 caption = "Table of mid-year Relative Spawning Biomass values for the bias adjust = 0.87 scenario.")
```

```{r ssb-biasadjust-table}
yr_start <- 2019
table_timeseries(ps_b,
                 type = "ssb",
                 yr_lim = c(yr_start, NA),
                 scen = 1:3,
                 inc_mean = FALSE,
                 caption = "Table of mid-year Spawning Biomass values for the three bias adjust scenarios.") %>% 
  kableExtra::kable_styling(font_size = 9)
```

```{r ssb-biasadjust0-table}
yr_start <- 2019
table_timeseries(ps_b,
                 type = "ssb",
                 yr_lim = c(yr_start, NA),
                 scen = 1,
                 by_country = TRUE,
                 inc_mean = FALSE,
                 caption = "Table of mid-year Spawning Biomass values by country for the bias adjust = 0.87 scenario.")
```

```{r ssb-biasadjust-by-country, fig.cap = "Bias adjustment scenarios Spawning biomass by country. Scenario label background colors match scenario colors in other plots."}
plot_timeseries(ps_b,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                show_40_10 = FALSE,
                facet_back_alpha = 50,
                rev_scenarios = TRUE)
```

```{r ssb-ssb0-biasadjust, fig.cap = "Bias adjustment scenarios relative spawning biomass."}
plot_timeseries(ps_b,
                type = "ssb_ssb0",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                rev_scenarios = TRUE)
```

```{r catch-biasadjust, fig.cap = "Catch plot for bias adjustment scenarios shows that future catch is zero."}
plot_timeseries(ps_b,
                type = "catch",
                ci_lines = FALSE,
                rev_scenarios = TRUE)
```

```{r aa-survey-biasadjust, fig.cap = "Average age in survey for the bias adjustment scenarios."}
plot_timeseries(ps_b,
                type = "aas",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                rev_scenarios = TRUE)
```

\clearpage

# Climate scenario

```{r tacv-climate, fig.cap = "TAC / Vulnerable biomass by season and country."}
plot_bars_country(ps_c,
                  facet_back_alpha = 50)
```

```{r ssb-climate, fig.cap = "Climate scenarios SSB in middle of the year."}
yr_start <- 2010
plot_timeseries(ps_c,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r ssb-climate-country, fig.cap = "Climate scenarios SSB in middle of the year by country."}
yr_start <- 2010
plot_timeseries(ps_c,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                show_40_10 = FALSE)
```

```{r ssb-ssb0-climate, fig.cap = "Climate scenarios relative spawning biomass."}
plot_timeseries(ps_c,
                type = "ssb_ssb0",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r catch-quota-climate, fig.cap = "Climate scenarios catch / quota."}
plot_timeseries(ps_c,
                type = "catch_quota",
                ci_lines = TRUE,
                yr_lim = c(yr_start, NA))
```

```{r catch-quota-climate-table}
yr_start <- 2019
table_timeseries(ps_c,
                 type = "catch_quota",
                 yr_lim = c(yr_start, NA),
                 scen = 1:3,
                 decimals = 3,
                 caption = "Catch / quota for the climate scenarios.") %>% 
    kableExtra::kable_styling(font_size = 9)
```

```{r pmetrics-climate, fig.cap = "Climate scenarios violin plots of performace metrics."}
plot_violins(ps_c)
```

```{r pmetrics-climate-table}
table_perf_metrics(ps_c, 
                   decimals = 3,
                   scen = c(1, 3),
                   caption = "Performance metrics for the climate scenarios.") %>% 
      kableExtra::kable_styling(font_size = 7)
```

```{r exploitation-climate, fig.cap = "Climate scenarios violin plots of exploitation rates by country. The three violin plots represent spring, summer, and fall respectively."}
plot_violins_country(ps_c, facet_back_alpha = 50)
```

```{r catch-climate, fig.cap = "Climate scenarios future projections of catch."}
#yr_start <- NA_real_
yr_start <- 2010
plot_timeseries(ps_c,
                type = "catch",
                yr_lim = c(yr_start, NA),
                ci_lines = FALSE)
```

```{r catch-climate-table}
yr_start <- 2019
table_timeseries(ps_c,
                 type = "catch",
                 yr_lim = c(yr_start, NA),
                 scen = 1,
                 decimals = 3,
                 caption = "Table of catch for the base climate scenario.")
```

```{r aa-catch-climate, fig.cap = "Climate scenarios average age in catch."}
plot_timeseries(ps_c,
                type = "aac",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r aa-catch-country-climate, fig.cap = "Climate scenarios average age in catch by country."}
plot_timeseries(ps_c,
                type = "aac",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                facet_back_alpha = 50)
```

```{r aa-catch-bycountry-climate-table}
yr_start <- 2040
table_timeseries(ps_c,
                 type = "aac",
                 yr_lim = c(yr_start, NA),
                 scen = 1,
                 decimals = 2,
                 by_country = TRUE,
                 caption = "Average age in the catch by country for the base climate scenario.")
```

```{r std-err-climate, fig.cap = "Climate scenarios standard error of estimated to real spawning stock biomass."}
plot_standard_error(ps_c,
                    facet_back_alpha = 50)
```

\clearpage

# HCR scenario

```{r tacv-hcr, fig.cap = "HCR scenarios TAC/V by season and country."}
plot_bars_country(ps_h,
                  facet_back_alpha = 50)
```

```{r ssb-hcr, fig.cap = "HCR scenarios SSB in middle of the year."}
yr_start <- 2010
plot_timeseries(ps_h,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r ssb-hcr-country, fig.cap = "Climate scenarios SSB in middle of the year by country."}
yr_start <- 2010
plot_timeseries(ps_h,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                show_40_10 = FALSE)
```

```{r ssb-ssb0-hcr, fig.cap = "HCR scenarios relative spawning biomass."}
plot_timeseries(ps_h,
                type = "ssb_ssb0",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))

```

```{r catch-quota-hcr, fig.cap = "HCR scenarios catch / quota."}
plot_timeseries(ps_h,
                type = "catch_quota",
                ci_lines = TRUE,
                yr_lim = c(yr_start, NA))
```

```{r pmetrics-hcr, fig.cap = "HCR scenarios violin plots of performace metrics."}
plot_violins(ps_h)
```

```{r exploitation-hcr, fig.cap = "HCR scenarios violin plots of exploitation rates by country. The three violin plots represent spring, summer, and fall respectively."}
plot_violins_country(ps_h, facet_back_alpha = 50)
```

```{r catch-hcr, fig.cap = "HCR scenarios future projections of catch."}
#yr_start <- NA_real_
yr_start <- 2010
plot_timeseries(ps_h,
                type = "catch",
                yr_lim = c(yr_start, NA),
                ci_lines = FALSE)
```

```{r aa-survey-hcr, fig.cap = "HCR scenarios average age in survey."}
yr_start <- 2010
plot_timeseries(ps_h,
                type = "aas",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r aa-catch-hcr, fig.cap = "HCR scenarios average age in catch."}
plot_timeseries(ps_h,
                type = "aac",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r aa-catch-country-hcr, fig.cap = "HCR scenarios average age in catch by country."}
plot_timeseries(ps_h,
                type = "aac",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                facet_back_alpha = 50)
```

```{r std-err-hcr, fig.cap = "HCR scenarios standard error of estimated to real spawning stock biomass."}
plot_standard_error(ps_h, facet_back_alpha = 50)
```

\clearpage

# Selectivity scenarios

```{r tacv-selectivity, fig.cap = "Selectivity scenarios TAC/V by season and country."}
plot_bars_country(ps_s,
                  facet_back_alpha = 50)
```

```{r ssb-selectivity, fig.cap = "Selectivity scenarios SSB in middle of the year."}
yr_start <- 2010
plot_timeseries(ps_s,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r ssb-selectivity-country, fig.cap = "Selectivity scenarios SSB in middle of the year by country."}
yr_start <- 2010
plot_timeseries(ps_s,
                type = "ssb",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                show_40_10 = FALSE)
```

```{r catch-quota-selectivity, fig.cap = "Selectivity scenarios catch / quota."}
plot_timeseries(ps_s,
                type = "catch_quota",
                ci_lines = TRUE,
                yr_lim = c(yr_start, NA))
```

```{r ssb-ssb0-selectivity, fig.cap = "Selectivity scenarios relative spawning biomass."}
plot_timeseries(ps_s,
                type = "ssb_ssb0",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r pmetrics-selectivity, fig.cap = "Selectivity scenarios violin plots of performace metrics."}
plot_violins(ps_s)
```

```{r exploitation-selectivity, fig.cap = "Selectivity scenarios violin plots of exploitation rates by country. The three violin plots represent spring, summer, and fall respectively."}
plot_violins_country(ps_s, facet_back_alpha = 50)
```

```{r catch-selectivity, fig.cap = "Selectivity scenarios future projections of catch."}
#yr_start <- NA_real_
yr_start <- 2010
plot_timeseries(ps_s,
                type = "catch",
                yr_lim = c(yr_start, NA),
                ci_lines = FALSE)
```

```{r aa-survey-selectivity, fig.cap = "Selectivity scenarios average age in survey."}
yr_start <- 2010
plot_timeseries(ps_s,
                type = "aas",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r aa-catch-selectivity, fig.cap = "Selectivity scenarios average age in catch."}
plot_timeseries(ps_s,
                type = "aac",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA))
```

```{r aa-catch-country-selectivity, fig.cap = "Selectivity scenarios average age in catch by country."}
plot_timeseries(ps_s,
                type = "aac",
                ci_lines = FALSE,
                yr_lim = c(yr_start, NA),
                by_country = TRUE,
                facet_back_alpha = 50)
```

```{r std-err-selectivity, fig.cap = "Selectivity scenarios standard error of estimated to real spawning stock biomass."}
plot_standard_error(ps_s)
```




